services:
  nordvpn:
    image: bubuntux/nordvpn
    container_name: nordvpn
    environment:
      - TOKEN=${TOKEN}
      - CONNECT=${NORDVPN_CONNECT}
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_ENV: development
      DATABASE_URL: postgresql://travelease:password@db:5432/travelease
    volumes:
      - ./backend:/app
    network_mode: "service:nordvpn"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d  
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U travelease -d travelease"]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      
volumes:
  db_data:
  postgres_data: